#!/bin/bash
DATE=`date -I`
NOWTIME=`date +"%H%M%S"`
RMDATE=`date -I -d '-31 day'`
USER=''
PASS=''
MYSQLSERVER=''
DIR=/data/backup/mysql/
DEST=${DIR}${DATE}
MYCNF=/tmp/$$.my.cnf


echo "[client]
user=${USER}
password=${PASS}
port=3306
host=${MYSQLSERVER}" > ${MYCNF}

IGNORE="information_schema performance_schema"

if [ ! -d ${DEST} ]
then
    mkdir -p ${DEST}
fi

# Single run or all databases
    if [ $1 ]
    then
        check_me=`mysql --defaults-extra-file=${MYCNF} -Bse 'show databases' | grep "$1"`
        if [ "${check_me}" != "" ]
        then
            DB_LIST=${check_me}
        else
            echo "Database $1 not found for single backup!"
            exit 1
        fi
    else
            DB_LIST=`mysql --defaults-extra-file=${MYCNF} -Bse 'show databases'`
    fi

for db in $DB_LIST; do
    skip=0
    if [ "$IGNORE" != "" ]; then
        for i in $IGNORE; do
            [ "$db" == "$i" ] && skip=1 || :
        done
    fi
    if [ "$skip" == "0" ]; then
    # echo "Dumping $db"
    logger -t sql-backup "Dumping ${db}"
        if [ -f "${DEST}/$db.sql.gz" ]
        then
            mysqldump --defaults-extra-file=${MYCNF} --trigger $db | gzip -c - > ${DEST}/$db-${NOWTIME}.sql.gz
        else
            mysqldump --defaults-extra-file=${MYCNF} --trigger $db | gzip -c - > ${DEST}/$db.sql.gz
        fi
    fi

done

rm ${MYCNF}

# Skip removing old backups if single database backup was requested
if [ $1 ]; then exit; fi

# Remove old backups
if [[ "`echo ${RMDATE} | awk -F'-' {' print $3 '}`" != "01" ]]
then
    if [ -d ${DIR}/$RMDATE ]
    then
        rm -r ${DIR}$RMDATE
    fi
fi
